// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"


namespace OverlayModeTags
{
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel);
}

namespace LocomotionActionTags
{
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ragdoll);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Vault);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mantle);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Hurdle);
}

namespace FoleyTags
{
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(None);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Run);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RunBackwds);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(RunStrafe);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Scuff);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScuffPivot);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walk);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(WalkBackwds);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jump);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Land);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Handplant);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScuffWall);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Tumble);
}
