// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"


namespace OverlayModeTags
{
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Default);
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Masculine)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Feminine)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Injured)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(HandsTied)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Rifle)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolOneHanded)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PistolTwoHanded)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Bow)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Torch)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Binoculars)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Box)
	GASP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Barrel)
}
